version: "3"

networks:
  gitea:

volumes:
  gitea:

services:
  server:
    image: gitea/gitea:1.15.7
    container_name: gitea
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
