version: "2.1"

volumes:
  heimdall_config:
  
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - heimdall_config:/config
    ports:
      - 80:80
    restart: unless-stopped
