version: "3.3"

volumes:
  homeassistant_data:

services:
  app:
    image: homeassistant/home-assistant
    restart: unless-stopped
    ports:
      - 8123:8123
    volumes:
      - homeassistant_data:/config
    environment:
      - TZ=America/Chicago
