version: "3"

volumes:
  neo4jdata:

services:
  neo4j:
    image: neo4j:4.4.14-community
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4jdata:/data
    environment:
      - NEO4J_AUTH=none
    restart: unless-stopped
