version: "3.3"

volumes:
  nextcloud_data:

services:
  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - SQLITE_DATABASE=nextcloud.db
      - NEXTCLOUD_ADMIN_USER=githubchange
      - NEXTCLOUD_ADMIN_PASSWORD=githubchange
      - NEXTCLOUD_TRUSTED_DOMAINS=""githubserver githubserver2""
