version: "3.3"

volumes:
  node-red-data:

services:
  node-red:
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    ports:
      - "8880:1880"
    volumes:
      - node-red-data:/data
