version: '3.1'
volumes:
  postgres:

services:
  db:
    image: postgres:alpine3.16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: githubchange
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
