version: '3.1'
volumes:
  prometheus_config:
  prometheus_data:
  grafana_config:
  grafana_data:

services:
  pushgateway:
    image: prom/pushgateway
    restart: unless-stopped
    ports:
      - 9091:9091
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    depends_on:
      - pushgateway
    volumes:
      - prometheus_config:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=5y'
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    volumes:
      - grafana_config:/etc/grafana/
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
